Syncthing - Combined init file
Put Syncthing and inotify into the same init.d script

diff --git a/syncthing/syncthing.init b/syncthing/syncthing.init
--- a/syncthing/syncthing.init
+++ b/syncthing/syncthing.init
@@ -1,132 +1,147 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides: syncthing
-# Required-Start: $local_fs $remote_fs
-# Required-Stop: $local_fs $remote_fs
-# Should-Start: $network
-# Should-Stop: $network
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
-# Short-Description: Syncthing Daemon
-# Description: Syncthing replaces proprietary sync and cloud services with something open,
-#              trustworthy and decentralized.
-#              Your data is your data alone and you deserve to choose where it is stored,
-#              if it is shared with some third party and how it's transmitted over the Internet.
+# Provides:          Syncthing-daemon
+# Required-Start:    $local_fs $remote_fs
+# Required-Stop:     $local_fs $remote_fs
+# Should-Start:      $network
+# Should-Stop:       $network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Daemonized version of Syncthing and webui.
+# Description:       Starts the Syncthing daemon with the user specified in
+#                    /etc/default/syncthing-daemon.
 ### END INIT INFO
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="Syncthing"
-NAME=syncthing
-DIR=/usr/bin
-DAEMON=$DIR/$NAME
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
-LOGFILE=/var/log/syncthing
-DAEMON_ARGS=" -no-browser -no-restart -logflags=0"
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+SYNCTHING_USER=REPLACEME
+DESC="Syncthing Daemon"
+NAME1="syncthing"
+NAME2="syncthing-inotify"
+DAEMON1=/usr/bin/syncthing
+DAEMON1_ARGS=" -no-browser -no-restart -logflags=0"
+DAEMON2=/usr/bin/syncthing-inotify
+DAEMON2_ARGS=" -logflags=0"
+PIDFILE1=/var/run/$NAME1.pid
+PIDFILE2=/var/run/$NAME2.pid
+UMASK=022
+PKGNAME=syncthing
+SCRIPTNAME=/etc/init.d/$PKGNAME
 
-# Permissions
-USER=REPLACEME
-GROUP=REPLACEME
+# Exit if the package is not installed
+[ -x "$DAEMON1" -a -x "$DAEMON2" ] || exit 0
 
-[ -x "$DAEMON" ] || exit 0
-
-. /lib/init/vars.sh
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-do_start() {
-	if [ -e $PIDFILE ]; then
-		PID=$(cat $PIDFILE)
-
-		if ( ps -p $PID > /dev/null ); then
-			log_failure_msg "$DESC '$NAME' is already running."
-			return 1
-		else
-			rm -f $PIDFILE
-
-			start-stop-daemon --start --background --chdir $DIR --chuid $USER:$GROUP --make-pidfile --pidfile $PIDFILE --quiet --iosched idle --nicelevel 19 --exec $DAEMON --test > /dev/null || return 1
-			start-stop-daemon --start --chdir $DIR --chuid $USER:$GROUP --make-pidfile --pidfile $PIDFILE --quiet --iosched idle --nicelevel 19 --exec $DAEMON -- $DAEMON_ARGS >> $LOGFILE 2>&1 &
-		fi
-	else
-		start-stop-daemon --start --background --chdir $DIR --chuid $USER:$GROUP --make-pidfile --pidfile $PIDFILE --quiet --iosched idle --nicelevel 19 --exec $DAEMON --test > /dev/null || return 1
-		start-stop-daemon --start --chdir $DIR --chuid $USER:$GROUP --make-pidfile --pidfile $PIDFILE --quiet --iosched idle --nicelevel 19 --exec $DAEMON -- $DAEMON_ARGS >> $LOGFILE 2>&1 &
-		# || return 2
-	fi
+#
+# Function to verify if a pid is alive
+#
+is_alive()
+{
+   pid=`cat $1` > /dev/null 2>&1
+   kill -0 $pid > /dev/null 2>&1
+   return $?
 }
 
-do_stop() {
-	if [ -e $PIDFILE ]; then
-		PID=$(cat $PIDFILE)
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+   # Return
+   #   0 if daemon has been started
+   #   1 if daemon was already running
+   #   2 if daemon could not be started
 
-		if ( ps -p $PID > /dev/null ); then
-			start-stop-daemon --stop --retry 1 --signal 2 --quiet --pidfile $PIDFILE
-			[ "$?" = 2 ] && return 2
-		else
-			log_failure_msg "$DESC '$NAME' is not running."
-			rm -f $PIDFILE
-			return 1
-		fi
-	else
-		log_failure_msg "$DESC '$NAME' is not running."
-		return 1
-	fi
+   is_alive $PIDFILE1
+   RETVAL1="$?"
+
+   if [ $RETVAL1 != 0 ]; then
+       rm -f $PIDFILE1
+       start-stop-daemon --start --background --quiet --pidfile $PIDFILE1 --make-pidfile \
+       --exec $DAEMON1 --chuid $SYNCTHING_USER --user $SYNCTHING_USER --umask $UMASK -- $DAEMON1_ARGS
+       RETVAL1="$?"
+   else
+       is_alive $PIDFILE2
+       RETVAL2="$?"
+       [ "$RETVAL2" = "0" -a "$RETVAL1" = "0" ] && return 1
+   fi
+
+   is_alive $PIDFILE2
+   RETVAL2="$?"
+
+   if [ $RETVAL2 != 0 ]; then
+        sleep 2
+        rm -f $PIDFILE2
+        start-stop-daemon --start --background --quiet --pidfile $PIDFILE2 --make-pidfile \
+        --exec $DAEMON2 --chuid $SYNCTHING_USER --user $SYNCTHING_USER --umask $UMASK -- $DAEMON2_ARGS
+        RETVAL2="$?"
+   fi
+   [ "$RETVAL1" = "0" -a "$RETVAL2" = "0" ] || return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+   # Return
+   #   0 if daemon has been stopped
+   #   1 if daemon was already stopped
+   #   2 if daemon could not be stopped
+   #   other if a failure occurred
+
+   start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $SYNCTHING_USER --pidfile $PIDFILE2
+   RETVAL2="$?"
+   start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --user $SYNCTHING_USER --pidfile $PIDFILE1
+   RETVAL1="$?"
+   [ "$RETVAL1" = "2" -o "$RETVAL2" = "2" ] && return 2
+
+   rm -f $PIDFILE1 $PIDFILE2
+
+   [ "$RETVAL1" = "0" -a "$RETVAL2" = "0" ] && return 0 || return 1
 }
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC..." "$NAME"
-		do_start
-
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			1) log_end_msg 1 ;;
-		esac
-	;;
-	stop)
-		log_daemon_msg "Stopping $DESC..." "$NAME"
-		do_stop
-
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			2) log_end_msg 1 ;;
-		esac
-	;;
-	restart)
-		log_daemon_msg "Restarting $DESC..." "$NAME"
-		do_stop
-
-		case "$?" in
-			0|1)
-				do_start
-
-				case "$?" in
-					0) log_end_msg 0 ;;
-					*) log_end_msg 1 ;;
-				esac
-			;;
-			*)
-				log_end_msg 1
-			;;
-		esac
-	;;
-	status)
-		if [ -e $PIDFILE ]; then
-			PID=$(cat $PIDFILE)
-
-			if ( ps -p $PID > /dev/null ); then
-				log_success_msg "$DESC '$NAME' is running (pid $PID)."
-				exit 0
-			else
-				log_failure_msg "$DESC '$NAME' is not running."
-				rm -f $PIDFILE
-				exit 1
-			fi
-		else
-			log_failure_msg "$DESC '$NAME' is not running."
-			exit 1
-		fi
-	;;
-	*)
-		log_action_msg "Usage: $SCRIPTNAME {start|stop|restart|status}"
-		exit 0
-	;;
+  start)
+   [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME1"
+   do_start
+   case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+   esac
+   ;;
+  stop)
+   [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME1"
+   do_stop
+   case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+   esac
+   ;;
+  restart|force-reload)
+   log_daemon_msg "Restarting $DESC" "$NAME1"
+   do_stop
+   case "$?" in
+     0|1)
+      do_start
+      case "$?" in
+         0) log_end_msg 0 ;;
+         1) log_end_msg 1 ;; # Old process is still running
+         *) log_end_msg 1 ;; # Failed to start
+      esac
+      ;;
+     *)
+        # Failed to stop
+      log_end_msg 1
+      ;;
+   esac
+   ;;
+  *)
+   echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+   exit 3
+   ;;
 esac
+
+:
